name: npmjs

on:
    push:
    pull_request:
    release:
        types:
            - published

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target: ['Node']
                node: ['14', '16']
                include:
                    - target: Web
                      node: 16
                      browser: Firefox
                    - target: Web
                      node: 16
                      browser: Chromium
                    - target: Web
                      node: 16
                      browser: WebKit
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              id: cache
              with:
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                  key: ${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  registry-url: https://registry.npmjs.org/
            - run: npm install -g npm@^6
            - if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - if: matrix.node == '16' && matrix.browser == 'webkit'
              run: sudo npx playwright install-deps
            - run: ENV=${{ matrix.target }} BROWSER=${{ matrix.browser }} npm test
            - id: benchmarks
              run: |
                  ENV=${{ matrix.target }} BROWSER=${{ matrix.browser }} npm run benchmarks
                  BENCHMARKS_SUMMARY=$(cat $GITHUB_STEP_SUMMARY)
                  echo "result=$BENCHMARKS_SUMMARY >> $GITHUB_OUTPUT"
            - uses: marocchino/sticky-pull-request-comment@v2
              if: matrix.target == 'Node'
              with:
                  header: Node ${{ matrix.node }}
                  message: ${{ steps.benchmarks.outputs.result }}
            - uses: marocchino/sticky-pull-request-comment@v2
              if: matrix.target == 'Web'
              with:
                  header: ${{ matrix.browser}}
                  message: |
                      ${{ steps.benchmarks.outputs.result }}
            - if: github.event_name == 'release' && github.event.action == 'published' && matrix.node == '16' && matrix.target == 'node'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
